import images from "./images";

export const General_links = [
  {
    name: "All Users",
    link: "/all-users",
    icon: images.Users,
     sublinks: [],
     permission: "all_users.view",
  },
  {
    name: "Balance",
    link: "/balance",
    icon: images.balance,
     sublinks: [],
     permission: "balance.view",
  },
  {
    name: "Chats",
    link: "/chats",
    icon: images.chats,
     sublinks: [],
     permission: "chats.view",
  },
  {
    name: "Analytics",
    link: "/analytics",
    icon: images.analytics,
     sublinks: [],
     permission: "analytics.view",
  },
  {
    name: "Leaderboard",
    link: "/leaderboard",
    icon: images.leaderboard,
     sublinks: [],
     permission: "leaderboard.view",
  },
  {
    name: "Support",
    link: "/support",
    icon: images.support,
     sublinks: [],
     permission: "support.view",
  },
  {
    name: "Disputes",
    link: "/disputes",
    icon: images.disputes,
     sublinks: [],
     permission: "disputes.view",
  },
  {
    name: "Withdraw Requests",
    link: "/withdrawal-requests",
    icon: images.transaction,
     sublinks: [],
     permission: "withdrawals.view",
  },
  {
    name: "Ratings & Reviews",
    link: "/ratings-reviews",
    icon: images.ratingsreviews,
     sublinks: [],
     permission: "ratings.view",
  },
  {
    name: "Referral Mgt",
    link: "/referral-mgt",
    icon: images.referralmgt,
     sublinks: [],
     permission: "referrals.view",
  },
  {
    name: "Notifications",
    link: "/notifications",
    icon: images.notifications,
     sublinks: [],
     permission: "notifications.view",
  },
  {
    name: "Seller Help Requests",
    link: "/seller-help-requests",
    icon: images.support,
     sublinks: [],
     permission: "seller_help.view",
  },
  {
    name: "Role Management",
    link: "/role-management",
    icon: images.settings,
     sublinks: [],
     permission: "settings.admin_management", // Only admins can access
  },
  {
    name: "Settings",
    link: "/settings",
    icon: images.settings,
     sublinks: [],
     permission: "settings.view",
  },
  {
    name: "Account Officer Vendors",
    link: "/account-officer-vendors",
    icon: images.Users,
     sublinks: [],
     permission: "account_officer_vendors.view",
  },
];
