const images = {

  logo : "/assets/sidebar/logo.png",
  dashboard: "/assets/sidebar/dashboard.svg",
  Users: "/assets/sidebar/Users.svg",
  admin : "/assets/layout/admin.png",
  orders: "/assets/sidebar/orders.svg",
  transaction: "/assets/sidebar/transaction.svg",
  products: "/assets/sidebar/products.svg",
  store: "/assets/sidebar/store.svg",
  subscriptions: "/assets/sidebar/subscriptions.svg",
  promotions: "/assets/sidebar/promotions.svg",
  socialfeed: "/assets/sidebar/socialfeed.svg",
  settings: "/assets/sidebar/settings.svg",
  balance: "/assets/sidebar/balance.svg",
  chats: "/assets/sidebar/chats.svg",
  analytics: "/assets/sidebar/analytics.svg",
  leaderboard: "/assets/sidebar/leaderboard.svg",
  support: "/assets/sidebar/support.svg",
  ratingsreviews: "/assets/sidebar/ratings-reviews.svg",
  referralmgt: "/assets/sidebar/referral-mgt.svg",
  notifications: "/assets/sidebar/notifications.svg",
  logout : "/assets/sidebar/logout.svg",
  dropdown: "/assets/layout/dropdown.svg",
  analyticsIcon: "/assets/layout/analytics.svg",
  money: "/assets/layout/money.svg",
  sasha: "/assets/layout/sasha.png",
  eye: "/assets/layout/eye.svg",
  bella: "/assets/layout/bella.png",
  jennifer: "/assets/layout/jennifer.png",
  carter: "/assets/layout/carter.png",
  chris: "/assets/layout/chris.png",
  daisy: "/assets/layout/daisy.png",
  emma: "/assets/layout/emma.png",
  ethens: "/assets/layout/ethens.png",
  tom: "/assets/layout/tom.png",
  MagnifyingGlass: "/assets/layout/MagnifyingGlass.svg",
  dots: "/assets/layout/dots.svg",
  block: "/assets/layout/block.svg",
  ban: "/assets/layout/ban.svg",
  close: "/assets/layout/close.svg",
  img: "/assets/layout/img.svg",
  edit: "/assets/layout/edit.svg",
  bell: "/assets/layout/bell.svg",
  dot: "/assets/layout/dot.svg",
  cycle: "/assets/layout/cycle.svg",
  cart: "/assets/layout/cart.svg",
  tick: "/assets/layout/tick.svg",
  iphone: "/assets/layout/iphone.png",
  ivideo: "/assets/layout/ivideo.png",
  video: "/assets/layout/video.svg",
  i1: "/assets/layout/i1.png",
  i2: "/assets/layout/i2.png",
  i3: "/assets/layout/i3.png",
};

export default images;
